let stickyItems:ScratchItem[]=[],stickyLoading=false,stickyScope='all',stickyFilter='open',stickyLast='',stickyRequest=0;
type Appearance={theme:'light'|'dark'|'system';accent:string;font:number;sidebar:number;width:number;tool:number;notes:boolean;compact:boolean;path:boolean};
const defaultAppearance:Appearance={theme:'light',accent:'blue',font:14,sidebar:248,width:820,tool:42,notes:true,compact:false,path:true};
let appearance:Appearance={...defaultAppearance};
function parseAppearance(raw:string|null):Appearance{
 try{const v=JSON.parse(raw||'{}');return {theme:['light','dark','system'].includes(v.theme)?v.theme:'light',accent:['blue','green','purple'].includes(v.accent)?v.accent:'blue',font:Math.max(12,Math.min(18,Number(v.font)||14)),sidebar:Math.max(180,Math.min(420,Number(v.sidebar)||248)),width:Math.max(640,Math.min(1100,Number(v.width)||820)),tool:Math.max(22,Math.min(75,Number(v.tool)||42)),notes:v.notes!==false,compact:v.compact===true,path:v.path!==false}}catch{return {...defaultAppearance}}
}
function installStickyBoard(){
 try{stickyScope=localStorage.getItem('jianzuo-sticky-scope')||'all';stickyFilter=localStorage.getItem('jianzuo-sticky-filter')||'open'}catch{}
 element('task-list').insertAdjacentHTML('afterend','<section id="sticky-board" class="sticky-board"><header><strong>待办</strong><span id="sticky-count" class="muted"></span><button id="sticky-expand" type="button" aria-expanded="false" aria-controls="sticky-list sticky-filter sticky-scope" aria-label="展开待办和筛选">展开</button><select id="sticky-filter" aria-label="待办筛选"><option value="open">未完成</option><option value="all">全部</option><option value="done">已完成</option></select><select id="sticky-scope" aria-label="待办范围"><option value="all">全部任务</option><option value="task">本任务</option></select><button id="sticky-new" title="新建待办">＋</button></header><div id="sticky-list" class="sticky-list"></div></section>');
 button('sticky-expand').onclick=()=>{const board=element('sticky-board');board.dataset.mobileExpanded=board.dataset.mobileExpanded==='true'?'false':'true';syncStickyCompact(board.dataset.empty==='true')};
 input('sticky-scope').value=stickyScope;input('sticky-scope').onchange=()=>{stickyScope=input('sticky-scope').value;try{localStorage.setItem('jianzuo-sticky-scope',stickyScope)}catch{}renderStickyBoard()};
 input('sticky-filter').value=stickyFilter;input('sticky-filter').onchange=()=>{stickyFilter=input('sticky-filter').value;try{localStorage.setItem('jianzuo-sticky-filter',stickyFilter)}catch{}renderStickyBoard()};
 button('sticky-new').onclick=()=>{if(!chosen){notify('先选择一个任务，便签会保存在该任务中。');return}editScratch(null)};
 button('scratch-tab').classList.add('hidden');stickyLast='';void loadStickyBoard();
}
async function loadStickyBoard(){if(!authenticated||!element('sticky-list')||stickyLoading)return;stickyLoading=true;const request=++stickyRequest;try{const items=await api<ScratchItem[]>('scratch');if(request!==stickyRequest)return;stickyItems=items;renderStickyBoard()}catch(e){if(element('sticky-list')&&!stickyItems.length){syncStickyCompact(false);element('sticky-list').textContent=(e as Error).message}}finally{stickyLoading=false}}
function syncStickyCompact(empty:boolean){
 const board=element('sticky-board'),toggle=element('sticky-expand');if(!board||!toggle)return;
 board.dataset.empty=String(empty);
 const expanded=!empty||board.dataset.mobileExpanded==='true';
 toggle.setAttribute('aria-expanded',String(expanded));toggle.setAttribute('aria-label',expanded?'收起空待办和筛选':'展开待办和筛选');toggle.textContent=expanded?'收起':'展开';
}
function renderStickyBoard(){
 if(!element('sticky-list'))return;
 const scoped=stickyItems.filter(n=>stickyScope!=='task'||n.task_id===chosen);
 const items=scoped.filter(n=>{const s=scratchStatus(n);return stickyFilter==='all'||(stickyFilter==='open'?s!=='done':s==='done')});
 syncStickyCompact(items.length===0);
 const html=items.map(n=>scratchCardHTML(n,'all')).join('')||`<p class="muted">${stickyFilter==='done'?'还没有完成的待办。':'点 ＋ 记下一步要做的事，勾选即可完成。'}</p>`;
 if(element('sticky-count'))element('sticky-count').textContent=scoped.filter(n=>scratchStatus(n)!=='done').length+' 项未完成';
 if(html===stickyLast)return;stickyLast=html;element('sticky-list').innerHTML=html;
 element('sticky-list').querySelectorAll<HTMLInputElement>('[data-toggle]').forEach(box=>box.onclick=()=>void toggleScratch(stickyItems.find(n=>n.id===box.dataset.toggle),box.checked));
 element('sticky-list').querySelectorAll<HTMLButtonElement>('[data-edit]').forEach(b=>b.onclick=()=>editScratch(stickyItems.find(n=>n.id===b.dataset.edit)||null));
 element('sticky-list').querySelectorAll<HTMLButtonElement>('[data-use]').forEach(b=>b.onclick=()=>useScratchItem(stickyItems.find(n=>n.id===b.dataset.use)));
 element('sticky-list').querySelectorAll<HTMLButtonElement>('[data-delete]').forEach(b=>b.onclick=()=>void deleteScratch(stickyItems.find(n=>n.id===b.dataset.delete)));
}
setInterval(()=>{if(authenticated&&!document.hidden&&element('sticky-board'))void loadStickyBoard()},5000);
function applyAppearance(value:Appearance){const root=document.documentElement;root.dataset.theme=value.theme==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):value.theme;root.dataset.accent=value.accent;root.dataset.density=value.compact?'compact':'normal';root.style.setProperty('--chat-font',value.font+'px');root.style.setProperty('--sidebar-width',value.sidebar+'px');root.style.setProperty('--chat-width',value.width+'px');element('workspace')?.style.setProperty('--tool-width',value.tool+'%');element('sticky-board')?.classList.toggle('hidden',!value.notes);element('task-workspace')?.classList.toggle('hidden',!value.path)}
function installAppearance(){try{appearance=parseAppearance(localStorage.getItem('jianzuo-appearance-v1'));if(!localStorage.getItem('jianzuo-appearance-v1')&&localStorage.getItem('jianzuo-theme')==='dark')appearance.theme='dark'}catch{}applyAppearance(appearance);
 element('root').insertAdjacentHTML('beforeend',`<dialog id="appearance-dialog"><form id="appearance-form"><h2>调整界面</h2><div class="form-grid"><div><label for="appearance-theme">主题</label><select id="appearance-theme"><option value="light">浅色</option><option value="dark">深色</option><option value="system">跟随系统</option></select></div><div><label for="appearance-accent">强调色</label><select id="appearance-accent"><option value="blue">蓝色</option><option value="green">绿色</option><option value="purple">紫色</option></select></div></div><label for="appearance-font">对话字号</label><input id="appearance-font" type="range" min="12" max="18" step="1"><label for="appearance-sidebar">任务侧栏宽度</label><input id="appearance-sidebar" type="range" min="180" max="420" step="5"><label for="appearance-tool">左右工具栏宽度</label><input id="appearance-tool" type="range" min="22" max="75" step="1"><label for="appearance-width">对话内容宽度</label><input id="appearance-width" type="range" min="640" max="1100" step="20"><label class="check-row"><input id="appearance-notes" type="checkbox">常驻便签</label><label class="check-row"><input id="appearance-compact" type="checkbox">紧凑布局</label><label class="check-row"><input id="appearance-path" type="checkbox">显示任务工作路径</label><p>即时预览，保存到当前浏览器。</p><div class="dialog-footer"><button type="button" id="appearance-layout">恢复默认布局</button><button type="button" id="appearance-reset">恢复默认</button><button type="button" id="appearance-cancel">取消</button><button class="primary">保存</button></div></form></dialog>`);
 button('theme-toggle').onclick=()=>{fillAppearance(appearance);element<HTMLDialogElement>('appearance-dialog').showModal()};element('appearance-form').oninput=()=>applyAppearance(readAppearance());element('appearance-form').onsubmit=e=>{e.preventDefault();appearance=readAppearance();try{localStorage.setItem('jianzuo-appearance-v1',JSON.stringify(appearance));localStorage.setItem('jianzuo-theme',appearance.theme)}catch{}applyAppearance(appearance);element<HTMLDialogElement>('appearance-dialog').close()};button('appearance-layout').onclick=()=>{resetPanelLayout();fillAppearance(appearance)};button('appearance-reset').onclick=()=>{fillAppearance(defaultAppearance);applyAppearance(defaultAppearance)};button('appearance-cancel').onclick=()=>{applyAppearance(appearance);element<HTMLDialogElement>('appearance-dialog').close()};element('appearance-dialog').addEventListener('cancel',()=>applyAppearance(appearance));
}
function fillAppearance(v:Appearance){for(const key of ['theme','accent','font','sidebar','width','tool'] as const)input('appearance-'+key).value=String(v[key]);for(const key of ['notes','compact','path'] as const)input('appearance-'+key).checked=v[key]}
function readAppearance():Appearance{return parseAppearance(JSON.stringify({theme:input('appearance-theme').value,accent:input('appearance-accent').value,font:input('appearance-font').value,sidebar:input('appearance-sidebar').value,tool:input('appearance-tool').value,width:input('appearance-width').value,notes:input('appearance-notes').checked,compact:input('appearance-compact').checked,path:input('appearance-path').checked}))}
