let stickyItems:ScratchItem[]=[],stickyLoading=false,stickyScope='all',stickyLast='',stickyRequest=0;
type Appearance={theme:'light'|'dark'|'system';accent:string;font:number;sidebar:number;width:number;tool:number;notes:boolean;compact:boolean;path:boolean};
const defaultAppearance:Appearance={theme:'light',accent:'blue',font:14,sidebar:248,width:820,tool:42,notes:true,compact:false,path:true};
let appearance:Appearance={...defaultAppearance};
function parseAppearance(raw:string|null):Appearance{
 try{const v=JSON.parse(raw||'{}');return {theme:['light','dark','system'].includes(v.theme)?v.theme:'light',accent:['blue','green','purple'].includes(v.accent)?v.accent:'blue',font:Math.max(12,Math.min(18,Number(v.font)||14)),sidebar:Math.max(180,Math.min(420,Number(v.sidebar)||248)),width:Math.max(640,Math.min(1100,Number(v.width)||820)),tool:Math.max(22,Math.min(75,Number(v.tool)||42)),notes:v.notes!==false,compact:v.compact===true,path:v.path!==false}}catch{return {...defaultAppearance}}
}
function installStickyBoard(){
 try{stickyScope=localStorage.getItem('jianzuo-sticky-scope')||'all'}catch{}
 element('task-list').insertAdjacentHTML('afterend','<section id="sticky-board" class="sticky-board"><header><strong>便签</strong><select id="sticky-scope" aria-label="便签范围"><option value="all">全部</option><option value="task">本任务</option></select><button id="sticky-new" title="新建便签">＋</button></header><div id="sticky-list" class="sticky-list"></div></section>');
 input('sticky-scope').value=stickyScope;input('sticky-scope').onchange=()=>{stickyScope=input('sticky-scope').value;try{localStorage.setItem('jianzuo-sticky-scope',stickyScope)}catch{}renderStickyBoard()};
 button('sticky-new').onclick=()=>{if(!chosen){notify('先选择一个任务，便签会保存在该任务中。');return}editScratch(null)};
 element('scratch-content').insertAdjacentHTML('beforebegin','<label for="scratch-color">便签颜色</label><select id="scratch-color"><option value="yellow">黄色</option><option value="green">绿色</option><option value="blue">蓝色</option><option value="pink">粉色</option><option value="purple">紫色</option></select>');
 button('scratch-tab').classList.add('hidden');stickyLast='';void loadStickyBoard();
}
async function loadStickyBoard(){if(!authenticated||!element('sticky-list')||stickyLoading)return;stickyLoading=true;const request=++stickyRequest;try{const items=await api<ScratchItem[]>('scratch');if(request!==stickyRequest)return;stickyItems=items;renderStickyBoard()}catch(e){if(element('sticky-list')&&!stickyItems.length)element('sticky-list').textContent=(e as Error).message}finally{stickyLoading=false}}
function renderStickyBoard(){if(!element('sticky-list'))return;const items=stickyItems.filter(n=>stickyScope!=='task'||n.task_id===chosen);const html=items.map(n=>`<article class="sticky-card" data-color="${escapeHTML(n.color||'yellow')}"><button class="sticky-content" data-sticky-edit="${n.id}" title="编辑便签">${escapeHTML(n.content.slice(0,240))}${n.content.length>240?'…':''}</button><footer><span title="${escapeHTML(n.task_title||'')}">${escapeHTML(n.task_title||'当前任务')}</span><button data-sticky-use="${n.id}" title="放入当前对话">↗</button><button data-sticky-delete="${n.id}" title="删除便签">×</button></footer></article>`).join('')||'<p class="muted">随手记录命令或线索<br>点击 ＋ 新建便签</p>';if(html===stickyLast)return;stickyLast=html;element('sticky-list').innerHTML=html;element('sticky-list').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=async()=>{const n=stickyItems.find(n=>n.id===(b.dataset.stickyEdit||b.dataset.stickyUse||b.dataset.stickyDelete));if(!n)return;if(b.dataset.stickyEdit)editScratch(n);else if(b.dataset.stickyUse){if(!chosen){notify('请先选择任务');return}bringToChat(n.content);renderWorkflow();element('sidebar').classList.remove('open')}else if(confirm('删除这条便签？')){try{await api(`tasks/${n.task_id}/scratch/${n.id}`,'DELETE',{revision:n.revision});await loadStickyBoard();if(toolsTab==='scratch')await loadScratch()}catch(e){notify((e as Error).message)}}})}
setInterval(()=>{if(authenticated&&!document.hidden&&element('sticky-board'))void loadStickyBoard()},5000);
function applyAppearance(value:Appearance){const root=document.documentElement;root.dataset.theme=value.theme==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):value.theme;root.dataset.accent=value.accent;root.dataset.density=value.compact?'compact':'normal';root.style.setProperty('--chat-font',value.font+'px');root.style.setProperty('--sidebar-width',value.sidebar+'px');root.style.setProperty('--chat-width',value.width+'px');element('workspace')?.style.setProperty('--tool-width',value.tool+'%');element('sticky-board')?.classList.toggle('hidden',!value.notes);element('task-workspace')?.classList.toggle('hidden',!value.path)}
function installAppearance(){try{appearance=parseAppearance(localStorage.getItem('jianzuo-appearance-v1'));if(!localStorage.getItem('jianzuo-appearance-v1')&&localStorage.getItem('jianzuo-theme')==='dark')appearance.theme='dark'}catch{}applyAppearance(appearance);
 element('root').insertAdjacentHTML('beforeend',`<dialog id="appearance-dialog"><form id="appearance-form"><h2>调整界面</h2><div class="form-grid"><div><label for="appearance-theme">主题</label><select id="appearance-theme"><option value="light">浅色</option><option value="dark">深色</option><option value="system">跟随系统</option></select></div><div><label for="appearance-accent">强调色</label><select id="appearance-accent"><option value="blue">蓝色</option><option value="green">绿色</option><option value="purple">紫色</option></select></div></div><label for="appearance-font">对话字号</label><input id="appearance-font" type="range" min="12" max="18" step="1"><label for="appearance-sidebar">任务侧栏宽度</label><input id="appearance-sidebar" type="range" min="180" max="420" step="5"><label for="appearance-tool">工具面板宽度</label><input id="appearance-tool" type="range" min="22" max="75" step="1"><label for="appearance-width">对话内容宽度</label><input id="appearance-width" type="range" min="640" max="1100" step="20"><label class="check-row"><input id="appearance-notes" type="checkbox">常驻便签</label><label class="check-row"><input id="appearance-compact" type="checkbox">紧凑布局</label><label class="check-row"><input id="appearance-path" type="checkbox">显示任务工作路径</label><p>即时预览，保存到当前浏览器。</p><div class="dialog-footer"><button type="button" id="appearance-layout">恢复默认布局</button><button type="button" id="appearance-reset">恢复默认</button><button type="button" id="appearance-cancel">取消</button><button class="primary">保存</button></div></form></dialog>`);
 button('theme-toggle').onclick=()=>{fillAppearance(appearance);element<HTMLDialogElement>('appearance-dialog').showModal()};element('appearance-form').oninput=()=>applyAppearance(readAppearance());element('appearance-form').onsubmit=e=>{e.preventDefault();appearance=readAppearance();try{localStorage.setItem('jianzuo-appearance-v1',JSON.stringify(appearance));localStorage.setItem('jianzuo-theme',appearance.theme)}catch{}applyAppearance(appearance);element<HTMLDialogElement>('appearance-dialog').close()};button('appearance-layout').onclick=()=>{resetPanelLayout();fillAppearance(appearance)};button('appearance-reset').onclick=()=>{fillAppearance(defaultAppearance);applyAppearance(defaultAppearance)};button('appearance-cancel').onclick=()=>{applyAppearance(appearance);element<HTMLDialogElement>('appearance-dialog').close()};element('appearance-dialog').addEventListener('cancel',()=>applyAppearance(appearance));
}
function fillAppearance(v:Appearance){for(const key of ['theme','accent','font','sidebar','width','tool'] as const)input('appearance-'+key).value=String(v[key]);for(const key of ['notes','compact','path'] as const)input('appearance-'+key).checked=v[key]}
function readAppearance():Appearance{return parseAppearance(JSON.stringify({theme:input('appearance-theme').value,accent:input('appearance-accent').value,font:input('appearance-font').value,sidebar:input('appearance-sidebar').value,tool:input('appearance-tool').value,width:input('appearance-width').value,notes:input('appearance-notes').checked,compact:input('appearance-compact').checked,path:input('appearance-path').checked}))}
