type ScratchItem={color?:string;task_id?:string;task_title?:string;id:string;content:string;revision:number;updated:number};
type DeviceConfig={id:string;kind?:string;relay?:{channel:number;contact:string;cycle_seconds:number};name:string;protocol:string;device:string;baud:number;host:string;port:number;user:string;fingerprint:string;read_only:boolean;data_bits?:number;parity?:string;stop_bits?:string;dtr?:boolean;rts?:boolean};
type DeviceEvent={seq:number;task_id?:string;direction:string;text:string;hex:string;created:number};
let toolsTab='',scratchItems:ScratchItem[]=[],scratchEditing:ScratchItem|null=null,scratchTask='',scratchOriginal='';
let devices:DeviceConfig[]=[],deviceID='',deviceTask='',deviceSeq=0,deviceEvents:DeviceEvent[]=[],devicePolling=false,deviceEditing:DeviceConfig|null=null;
function installTools(){
 element('task-model').insertAdjacentHTML('beforebegin','<button id="scratch-tab">便签</button><button id="hardware-tab">硬件调试</button>');
 element('notebook').insertAdjacentHTML('afterend',`<section id="scratch-panel" class="tool-panel hidden"><div class="note-head"><div><h2>便签</h2><p class="muted">随手记在当前任务里，需要时带入对话。</p></div><button id="scratch-new" class="primary">＋ 写便签</button></div><div id="scratch-list" class="scratch-grid"></div></section><section id="hardware-panel" class="tool-panel hidden"></section>`);
 element('root').insertAdjacentHTML('beforeend',`<dialog id="scratch-dialog"><form id="scratch-form"><h2>任务便签</h2><textarea id="scratch-content" rows="12" required maxlength="60000" aria-label="便签内容"></textarea><p id="scratch-error" class="error"></p><div class="dialog-footer"><button type="button" id="scratch-cancel">取消</button><button class="primary">保存便签</button></div></form></dialog><dialog id="device-dialog"><form id="device-form"><h2>硬件连接</h2><label for="device-name">名称</label><input id="device-name" required maxlength="80"><label for="device-protocol">协议</label><select id="device-protocol"><option value="serial">串口 · 服务电脑</option><option value="tcp">TCP 原始字节流</option><option value="telnet">Telnet</option><option value="ssh">SSH</option></select><div id="device-serial-fields"><label for="device-portname">串口</label><input id="device-portname" list="device-ports" placeholder="COM3"><datalist id="device-ports"></datalist><button type="button" id="device-refresh-ports">刷新串口</button><label for="device-baud">波特率 · 8N1</label><input id="device-baud" type="number" min="300" max="4000000" value="115200"></div><div id="device-network-fields"><label for="device-host">主机</label><input id="device-host" placeholder="192.168.50.20"><label for="device-port">端口</label><input id="device-port" type="number" min="1" max="65535"></div><div id="device-ssh-fields"><label for="device-user">SSH 用户名</label><input id="device-user" autocomplete="off"><label for="device-fingerprint">主机 SHA256 指纹</label><input id="device-fingerprint" placeholder="SHA256:…"><p>首次连接会显示指纹。核对设备后填入并保存，再连接。也支持服务用户 .ssh 目录中默认命名的未加密私钥。</p></div><label class="check-row"><input id="device-readonly" type="checkbox">只接收，不允许发送</label><p id="device-error" class="error"></p><div class="dialog-footer"><button id="device-delete" type="button" class="danger">删除连接</button><button id="device-cancel" type="button">取消</button><button class="primary">保存配置</button></div></form></dialog><dialog id="device-password-dialog"><form id="device-password-form"><h2>连接 SSH</h2><label for="device-password">密码（使用密钥时留空）</label><input id="device-password" type="password" autocomplete="off"><p>密码仅用于本次连接，不保存到配置或日志。</p><div class="dialog-footer"><button type="button" id="device-password-cancel">取消</button><button class="primary">连接</button></div></form></dialog>`);
 button('scratch-tab').onclick=()=>switchTab('scratch');button('hardware-tab').onclick=()=>switchTab('hardware');
 button('scratch-new').onclick=()=>editScratch(null);button('scratch-cancel').onclick=cancelScratch;element('scratch-dialog').addEventListener('cancel',e=>{e.preventDefault();cancelScratch()});
 element('scratch-form').onsubmit=async e=>{e.preventDefault();try{await api(`tasks/${scratchTask}/scratch`+(scratchEditing?'/'+scratchEditing.id:''),scratchEditing?'PUT':'POST',{content:input('scratch-content').value,revision:scratchEditing?.revision,color:input('scratch-color').value});element<HTMLDialogElement>('scratch-dialog').close();await loadScratch();await loadStickyBoard()}catch(e){element('scratch-error').textContent=(e as Error).message}};
 installHardware();
}
function bringToChat(text:string){const old=drafts.get(chosen)||'';drafts.set(chosen,old?old+'\n\n'+text:text);input('message').value=drafts.get(chosen)!;switchTab('chat');input('message').focus();notify('已放入输入框，确认后发送。')}
function cancelScratch(){if(input('scratch-content').value!==scratchOriginal&&!confirm('放弃未保存的便签修改？'))return;element<HTMLDialogElement>('scratch-dialog').close()}
function editScratch(n:ScratchItem|null){scratchEditing=n;scratchTask=n?.task_id||chosen;scratchOriginal=n?.content||'';input('scratch-content').value=scratchOriginal;input('scratch-color').value=n?.color||'yellow';element('scratch-error').textContent='';element<HTMLDialogElement>('scratch-dialog').showModal();input('scratch-content').focus()}
async function loadScratch(){const id=chosen;try{const items=await api<ScratchItem[]>(`tasks/${id}/scratch`);if(id!==chosen)return;scratchItems=items;element('scratch-list').innerHTML=items.map(n=>`<article class="scratch-card" data-color="${escapeHTML(n.color||'yellow')}"><small>${new Date(n.updated).toLocaleString()}</small><div>${escapeHTML(n.content)}</div><footer><button data-edit="${n.id}">编辑</button><button data-use="${n.id}">带入对话</button><button data-delete="${n.id}" class="subtle">删除</button></footer></article>`).join('')||'<p class="muted">还没有便签，记下命令、线索或下一步想做的事。</p>';element('scratch-list').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=async()=>{const n=scratchItems.find(n=>n.id===(b.dataset.edit||b.dataset.use||b.dataset.delete));if(!n)return;if(b.dataset.edit){editScratch(n)}else if(b.dataset.use){bringToChat(n.content)}else if(confirm('删除这条便签？')){try{await api(`tasks/${id}/scratch/${n.id}`,'DELETE',{revision:n.revision});await loadScratch()}catch(e){notify((e as Error).message)}}})}catch(e){notify((e as Error).message)}}

let toolFullscreen=false;
function installWorkspace(){
 const main=element('conversation').parentElement!;
 const workspace=document.createElement('div');workspace.id='workspace';
 const left=document.createElement('aside');left.id='dock-left';left.className='dock hidden';left.setAttribute('aria-label','左侧工具区');
 const right=document.createElement('aside');right.id='dock-right';right.className='dock hidden';right.setAttribute('aria-label','右侧工具区');
 const chat=document.createElement('div');chat.id='chat-column';
 const bottom=document.createElement('div');bottom.id='dock-bottom';bottom.className='dock-bottom dock hidden';bottom.setAttribute('aria-label','对话下方工具区');
 const dock=document.createElement('aside');dock.id='tool-dock';dock.className='hidden';dock.setAttribute('aria-label','任务工具');
 dock.innerHTML='<div id="tool-resizer" role="separator" tabindex="0" aria-label="调整工具宽度" aria-orientation="vertical" aria-valuemin="22" aria-valuemax="75"></div><header class="tool-dock-head"><strong id="tool-title">任务工具</strong><div class="actions"><button id="tool-expand" title="展开工具面板">全屏</button><button id="tool-close" aria-label="关闭工具面板">✕</button></div></header><div id="tool-body"></div>';
 main.append(workspace);workspace.append(left,chat,right);right.append(dock);chat.append(element('conversation'),bottom,element('composer-wrap'));for(const id of ['notebook','scratch-panel','hardware-panel'])element('tool-body').append(element(id));
 button('chat-tab').textContent='对话';button('tool-close').onclick=()=>switchTab('chat');button('tool-expand').onclick=()=>{toolFullscreen=!toolFullscreen;workspace.classList.toggle('tool-full',toolFullscreen);button('tool-expand').textContent=toolFullscreen?'分屏':'全屏'};
}

function installSettingsSections(){
 const form=element('settings-form'),heading=form.querySelector('h2')!,feishuHeading=form.querySelector('#setup-feishu')!.previousElementSibling!,error=element('settings-error'),footer=form.querySelector('.dialog-footer')!;
 const environment=document.createElement('section');environment.id='settings-environment';environment.className='settings-section';
 while(heading.nextSibling&&heading.nextSibling!==feishuHeading)environment.append(heading.nextSibling);
 const feishu=document.createElement('section');feishu.id='settings-feishu';feishu.className='settings-section hidden';
 let node:ChildNode|null=feishuHeading;while(node&&node!==error){const next:ChildNode|null=node.nextSibling;feishu.append(node);node=next}
 const manual=document.createElement('details');manual.className='manual-feishu';manual.innerHTML='<summary>手工配置已有机器人</summary>';
 const firstLabel=feishu.querySelector('label[for="feishu-id"]');if(firstLabel){while(firstLabel.previousSibling&&firstLabel.previousSibling!==feishu.querySelector('#setup-feishu'))feishu.removeChild(firstLabel.previousSibling);let n:ChildNode|null=firstLabel;while(n){const next:ChildNode|null=n.nextSibling;manual.append(n);n=next};feishu.append(manual)}
 feishu.insertBefore(feishu.querySelector('#feishu-state')!,manual);feishu.insertBefore(feishu.querySelector('#feishu-owner')!,manual);feishu.insertBefore(feishu.querySelector('#feishu-enabled')!.parentElement!,manual);
 const tabs=document.createElement('nav');tabs.className='settings-nav';tabs.setAttribute('aria-label','设置分类');tabs.innerHTML='<button type="button" data-settings="environment" class="selected">执行环境</button><button type="button" data-settings="feishu">飞书连接</button><button type="button" data-settings="access">访问地址</button>';
 const access=document.createElement('section');access.id='settings-access';access.className='settings-section hidden';access.innerHTML='<h3>从其他设备打开简作</h3><p>简作运行在这台电脑上，其他电脑或手机通过浏览器访问。远程访问前，请让两端连接同一 Tailscale 网络，并保持服务电脑开机。</p><label for="access-lan">局域网地址</label><input id="access-lan" type="url" placeholder="http://192.168.1.10:8789"><label for="access-tailscale">Tailscale 地址或域名</label><input id="access-tailscale" type="url" placeholder="http://100.100.100.10:8789"><p>保存后，新生成的飞书任务清单和详情卡片会显示这两个入口；详情入口会直接定位到对应任务。地址中不包含密码或登录令牌。</p><div id="access-preview" class="access-preview"></div><p>打开后仍需输入工作台密码。更换局域网、端口或设备后请更新地址。飞书内置浏览器打不开时，可复制地址到系统浏览器。</p>';
 form.insertBefore(tabs,error);form.insertBefore(environment,error);form.insertBefore(feishu,error);form.insertBefore(access,error);
 const saved=document.createElement('p');saved.id='settings-saved';saved.setAttribute('role','status');saved.style.color='var(--accent)';form.insertBefore(saved,footer);
 tabs.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{const page=b.dataset.settings!;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));for(const id of ['environment','feishu','access'])element('settings-'+id).classList.toggle('hidden',id!==page)});
 input('access-lan').oninput=renderAccessPreview;input('access-tailscale').oninput=renderAccessPreview;footer.classList.add('settings-footer');
}
function loadAccessSettings(){input('access-lan').value=settings.config.access?.lan||'';input('access-tailscale').value=settings.config.access?.tailscale||'';renderAccessPreview()}
function renderAccessPreview(){
 element('access-preview').innerHTML=[['局域网','access-lan'],['Tailscale','access-tailscale']].map(([name,id])=>{const value=input(id).value.trim();try{const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash||!['','/'].includes(u.pathname))return '';return `<a href="${escapeHTML(u.href)}" target="_blank" rel="noopener noreferrer">${name}打开 ↗<small>${escapeHTML(u.origin)}</small></a>`}catch{return ''}}).join('');
}
